IMAGE_NAME = "ubuntu/bionic64"
N = 2

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.synced_folder '.', '/vagrant', disabled: true


  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end

  config.vm.define "k8s-master" do |master|
    master.vm.box = IMAGE_NAME
    master.vm.network "private_network", ip: "192.168.50.10"
    master.vm.hostname = "k8s-master"
    master.vm.provider :virtualbox do |vb|
      vb.name = "k8s-master"
      vb.customize ["modifyvm", :id, "--memory", "2048"]
      vb.customize ["modifyvm", :id, "--groups", "/Kubernetes"]
      vb.customize ["modifyvm", :id, "--cpus", "2"]
    end
  end

  config.vm.define "k8s-minion1" do |master|
    master.vm.box = IMAGE_NAME
    master.vm.network "private_network", ip: "192.168.50.11"
    master.vm.hostname = "k8s-minion1"
    master.vm.provider :virtualbox do |vb|
      vb.name = "k8s-minion1"
      vb.customize ["modifyvm", :id, "--memory", "2048"]
      vb.customize ["modifyvm", :id, "--groups", "/Kubernetes"]
      vb.customize ["modifyvm", :id, "--cpus", "2"]
    end
  end

#  config.vm.define "minion2" do |master|
#    master.vm.box = IMAGE_NAME
#    master.vm.network "private_network", ip: "192.168.50.12"
#    master.vm.hostname = "minion2"
#    master.vm.provider :virtualbox do |vb|
#      vb.customize ["modifyvm", :id, "--memory", "2048"]
#      vb.customize ["modifyvm", :id, "--cpus", "2"]
#    end
#  end



#config.vm.define "etcd-1" do |master|
#  master.vm.box = IMAGE_NAME
#  master.vm.network "private_network", ip: "192.168.50.3"
#  master.vm.hostname = "etcd-1"
#  master.vm.provider :virtualbox do |vb|
#    vb.customize ["modifyvm", :id, "--memory", "1024"]
#    vb.customize ["modifyvm", :id, "--cpus", "1"]
#  end
#end
#
#config.vm.define "etcd-2" do |master|
#  master.vm.box = IMAGE_NAME
#  master.vm.network "private_network", ip: "192.168.50.4"
#  master.vm.hostname = "etcd-2"
#  master.vm.provider :virtualbox do |vb|
#    vb.customize ["modifyvm", :id, "--memory", "1024"]
#    vb.customize ["modifyvm", :id, "--cpus", "1"]
#  end
#end
#
#config.vm.define "etcd-3" do |master|
#  master.vm.box = IMAGE_NAME
#  master.vm.network "private_network", ip: "192.168.50.5"
#  master.vm.hostname = "etcd-3"
#  master.vm.provider :virtualbox do |vb|
#    vb.customize ["modifyvm", :id, "--memory", "1024"]
#    vb.customize ["modifyvm", :id, "--cpus", "1"]
#  end
#end



    #config.vm.define "nfs-server" do |master|
    #    master.vm.box = IMAGE_NAME
    #    master.vm.network "private_network", ip: "192.168.50.100"
    #    master.vm.hostname = "nfs-server"
    #end
#
#    config.vm.define "registry" do |master|
#        master.vm.box = IMAGE_NAME
#        master.vm.network "private_network", ip: "192.168.50.101"
#        master.vm.hostname = "registry"
#    end
#
#    (1..N).each do |i|
#        config.vm.define "node-#{i}" do |node|
#            node.vm.box = IMAGE_NAME
#            node.vm.network "private_network", ip: "192.168.50.#{i + 10}"
#            node.vm.hostname = "node-#{i}"
#        end
#    end
end
